repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.11
    hooks:
      - id: ruff-format # formatter
        types_or: [python, pyi, jupyter, toml]
      - id: ruff # linter
        types_or: [python, pyi, jupyter, toml]
        args: [--fix]
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.401
    hooks:
      - id: pyright
        additional_dependencies:
          [
            beartype,
            einops,
            jax,
            jaxtyping,
            optax,
            pytest,
            typing_extensions,
            wadler_lindig,
          ]
