# Generated by Django 5.2.1 on 2025-06-14 00:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=20)),
                ("symbol", models.CharField(max_length=10, unique=True)),
                (
                    "current_price",
                    models.DecimalField(decimal_places=10, default=1, max_digits=19),
                ),
                ("fraction_traded", models.PositiveIntegerField(default=2)),
            ],
        ),
    ]
