# Generated by Django 5.2.1 on 2025-05-14 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acctmgr", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="acctmgr.account",
            ),
        ),
    ]
