# Generated by Django 5.2.1 on 2025-05-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acctmgr", "0002_account_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="placeholder",
            field=models.BooleanField(default=False),
        ),
    ]
